### ISSUE TITLE
Request got an unexpected keyword argument 'json'

### ISSUE THREAD

**Issue by ConnorSMaynes** [kiwiz/gkeepapi#16]
python 3.4
I used pip to install

Code I Ran:

import gkeepapi
keep = gkeepapi.Keep()
keep.login( MYUSERNAME, MYPASSWORD )

Traceback:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\gkeepapi-0.10.2-py3.4.egg\gkeepapi\__init__.py", line 344, in login
  File "C:\Python34\lib\site-packages\gkeepapi-0.10.2-py3.4.egg\gkeepapi\__init__.py", line 539, in sync
  File "C:\Python34\lib\site-packages\gkeepapi-0.10.2-py3.4.egg\gkeepapi\__init__.py", line 249, in changes
  File "C:\Python34\lib\site-packages\gkeepapi-0.10.2-py3.4.egg\gkeepapi\__init__.py", line 167, in send
TypeError: request() got an unexpected keyword argument 'json'

**Comment by kiwiz** [comment]
Hi there, does this still happen on the newest version?

**Comment by ConnorSMaynes** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\conno\AppData\Local\Programs\Python\Python36\lib\site-packages\gkeepapi\__init__.py", line 367, in login
    self.sync()
  File "C:\Users\conno\AppData\Local\Programs\Python\Python36\lib\site-packages\gkeepapi\__init__.py", line 572, in sync
    self._parseNodes(changes['nodes'])
  File "C:\Users\conno\AppData\Local\Programs\Python\Python36\lib\site-packages\gkeepapi\__init__.py", line 596, in _parseNodes
    node = _node.from_json(raw_node)
  File "C:\Users\conno\AppData\Local\Programs\Python\Python36\lib\site-packages\gkeepapi\node.py", line 1419, in from_json
    node.load(raw)
  File "C:\Users\conno\AppData\Local\Programs\Python\Python36\lib\site-packages\gkeepapi\node.py", line 1307, in load
    self.blob = self.from_json(raw['blob'])
KeyError: 'blob'

**Comment by kiwiz** [comment]
Could you provide the contents of the `raw` variable at line 1307?

**Comment by kiwiz** [comment]
Hmm, do you remember how you created the note `1521767163062.159180.2069646320`? I've never seen an entry without a `title` before. Maybe that note is malformed in other ways.

If you load up https://keep.google.com/u/0/#NOTE/1521767163062.159180.2069646320 in your browser, does the note display? Is there anything odd about it?

**Comment by akshayeshenoi** [comment]
I got the same error.
```json
{
  "kind": "notes#node",
  "annotationsGroup": {
    "kind": "notes#annotationsGroup"
  },
  "parentServerId": "1YuS33pkNe-CHENeeP0dAIRodZkBAH2la2x_-AcJmBHK2NzSNkl7005a1cop6CEWFl4hNrGs",
  "nodeSettings": {
    "newListItemPlacement": "BOTTOM",
    "graveyardState": "EXPANDED",
    "checkedListItemsPolicy": "GRAVEYARD"
  },
  "parentId": "1521861649560.175049.950940739",
  "timestamps": {
    "kind": "notes#timestamps",
    "updated": "2018-03-24T03: 21: 13.864Z",
    "created": "2018-03-24T03: 21: 13.864Z"
  },
  "serverId": "1Y4IAO93t6q3QxN1qwCQhUtUMPGg3L5oe3QCzRNbMpGmxgI4ex48-hlkTT7PMYTyjNSPgeeKw",
  "type": "BLOB",
  "id": "1521861649568.022949.3480975598"
}
```
Seems like there's no 'blob' key in the json, and the browser doesn't open the note either.
However, turns out the `parentId` points to a note in the recycle bin. When I delete it from there, everything works as expected.

Any idea why this happens?

**Comment by dpalmigiano** [comment]
Same issue happens when I try to run the example code in both python 2.7 and python 3.6.

Any ideas how to fix this?

**Comment by akshayeshenoi** [comment]
Check if the note with the `parentId` exists.  
For me, it was present in the recycle bin. Deleting it from there solved the problem.

**Comment by kiwiz** [comment]
@dpalmigiano Can you reproduce this reliably? I'd like to hold off on fixing this till I can test it.

**Comment by kiwiz** [comment]
Fixed in #41

**Comment by philippgovernale** [comment]
I still have the issue that was first reported in this thread in version 0.11.3 using python 2.7

Traceback (most recent call last):
  File "keep.py", line 4, in <module>
    keep.login('*************@gmail.com', '*************')
  File "/usr/local/lib/python2.7/dist-packages/gkeepapi/__init__.py", line 519, in login
    self.load(auth, state, sync)
  File "/usr/local/lib/python2.7/dist-packages/gkeepapi/__init__.py", line 565, in load
    self.sync(True)
  File "/usr/local/lib/python2.7/dist-packages/gkeepapi/__init__.py", line 807, in sync
    changes = self._reminders_api.list()
  File "/usr/local/lib/python2.7/dist-packages/gkeepapi/__init__.py", line 428, in list
    json=params
  File "/usr/local/lib/python2.7/dist-packages/gkeepapi/__init__.py", line 205, in send
    response = self._send(**req_kwargs).json()
  File "/usr/local/lib/python2.7/dist-packages/gkeepapi/__init__.py", line 242, in _send
    return self._session.request(**req_kwargs)
TypeError: request() got an unexpected keyword argument 'json'
