### ISSUE TITLE
KeyError: 'thumbnailGeneratedTime'

### ISSUE THREAD

**Issue by tsbertalan** [kiwiz/gkeepapi#44]
I'm not sure if this is just a problem with ink drawings, or true of all nodes, but at the moment the little "Eat Breakfast" sample script fails for me because of a key error at this line:

https://github.com/kiwiz/gkeepapi/blob/fbb52ec1d52d5827cb91641e24c01dd611532f4b/gkeepapi/node.py#L1566

Commenting out that line allows the script to proceed.

**Comment by tsbertalan** [comment]
For reference, the demo script at the time of writing was 

```python
import gkeepapi

keep = gkeepapi.Keep()
success = keep.login(USER, PASS)

note = keep.createNote('Todo', 'Eat breakfast')
note.pinned = True
note.color = gkeepapi.node.ColorValue.Red
keep.sync()
```

and the dict `raw` that raised the error was:
```python
{u'drawingId': u'redacted',
 u'inkHash': u'8aadb1407ede000f',
 u'snapshotData': {u'byte_size': 110773,
                   u'extracted_text': u'redacted',
                   u'extraction_status': u'SUCCEEDED',
                   u'height': 2048,
                   u'is_uploaded': True,
                   u'kind': u'notes#blob',
                   u'mimetype': u'image/png',
                   u'type': u'IMAGE',
                   u'width': 1592},
 u'snapshotFingerprint': u'-3893770042857979766',
 u'snapshotProtoFprint': u'14552974030851571850'}
```

**Comment by tsbertalan** [comment]
The actual `KeyError` is caught at [L197](https://github.com/kiwiz/gkeepapi/blob/fbb52ec1d52d5827cb91641e24c01dd611532f4b/gkeepapi/node.py#L197) and re-raised as a `ParseException`.

**Comment by kiwiz** [comment]
Should be fixed via the above commit. :+1:

**Comment by tsbertalan** [comment]
I think it's still not working. After installing with 
```
pip install git+https://github.com/kiwiz/gkeepapi.git
```
I get a traceback ending with 
```
File "/home/tsbertalan/.virtualenvs/gkeep/local/lib/python2.7/site-packages/gkeepapi/node.py", line 639, in str_to_dt
    return datetime.datetime.strptime(tzs, cls.TZ_FMT)
TypeError: strptime() argument 1 must be string, not int
```

I'm not exactly sure where this timestamp is going, but maybe some sort of `time.now()` would be appropriate?

**Comment by kiwiz** [comment]
My bad, should be fixed on master now.

**Comment by arjunkc** [comment]
Throws a TypeError for me now. I get the following error

```
/usr/local/lib/python3.5/site-packages/gkeepapi/node.py in _load(self, raw)
   1564         self.snapshot.load(raw['snapshotData'])
   1565         self._snapshot_fingerprint = raw['snapshotFingerprint']
-> 1566         self._thumbnail_generated_time = NodeTimestamps.str_to_dt(raw.get('thumbnailGeneratedTime') or 0)
   1567         self._ink_hash = raw['inkHash']
   1568         self._snapshot_proto_fprint = raw['snapshotProtoFprint']

/usr/local/lib/python3.5/site-packages/gkeepapi/node.py in str_to_dt(cls, tzs)
    635             datetime.datetime: Datetime.
    636         """
--> 637         return datetime.datetime.strptime(tzs, cls.TZ_FMT)
    638 
    639     @classmethod

TypeError: strptime() argument 1 must be str, not int
```

**Comment by tsbertalan** [comment]
Yup, 93708227 does it for me.
